export const commonRoles = [
  "Web Developer",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "Graphic Designer",
  "UI/UX Designer",
  "Product Designer",
  "Data Analyst",
  "Data Scientist",
  "Product Manager",
  "Project Manager",
  "Digital Marketing Specialist",
  "Content Writer",
  "DevOps Engineer",
  "QA Engineer",
  "Business Analyst",
  "Sales Executive",
  "Customer Support Specialist",
  "HR Manager",
  "Accountant",
];